version: '3.9'
services:
  # Python Flask server
  flask:
    build: ./app/
    container_name: flask_Server
    environment:
      - FLASK_ENV=development
    ports:
      - "5001:5001"
    depends_on:
      - db

  # MongoDB dçatabase 
  db:
    image: mongo:latest
    hostname: mongodb
    container_name: mongo_database
    environment:
      MONGO_INITDB_DATABASE: mango_db
      MONGO_INITDB_ROOT_USERNAME: root       # MongoDB Root Username
      MONGO_INITDB_ROOT_PASSWORD: pass       # MongoDB Root Password
    volumes:
      - "./db/:/data/db"
    ports:
      - 27017:27017
